// <auto-generated />
using DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20190802134204_DbIdentityServerAPI")]
    partial class DbIdentityServerAPI
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Age");

                    b.Property<string>("Email");

                    b.Property<string>("IdentityNo");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Password");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Age = (short)29,
                            Email = "edizilkcakin@gmail.com",
                            IdentityNo = "12345678941",
                            LastName = "Ilkcakin",
                            Name = "Ediz",
                            Password = "123456",
                            Sex = "m"
                        },
                        new
                        {
                            ID = 2,
                            Age = (short)31,
                            Email = "onuruygur@gmail.com",
                            IdentityNo = "12345678942",
                            LastName = "Uygur",
                            Name = "Onur",
                            Password = "1234567",
                            Sex = "m"
                        },
                        new
                        {
                            ID = 3,
                            Age = (short)30,
                            Email = "coskunparlar@gmail.com",
                            IdentityNo = "12345678943",
                            LastName = "Parlar",
                            Name = "Coskun",
                            Password = "12345678",
                            Sex = "m"
                        },
                        new
                        {
                            ID = 4,
                            Age = (short)30,
                            Email = "sezaydogan@gmail.com",
                            IdentityNo = "12345678944",
                            LastName = "Dogan",
                            Name = "Sezay",
                            Password = "123456789",
                            Sex = "m"
                        },
                        new
                        {
                            ID = 5,
                            Age = (short)21,
                            Email = "esraergenc@gmail.com",
                            IdentityNo = "12345678945",
                            LastName = "Ergenc",
                            Name = "Esra",
                            Password = "123456780",
                            Sex = "f"
                        },
                        new
                        {
                            ID = 6,
                            Age = (short)29,
                            Email = "senemyildirim@gmail.com",
                            IdentityNo = "12345678946",
                            LastName = "Yildirim",
                            Name = "Senem",
                            Password = "123456781",
                            Sex = "f"
                        },
                        new
                        {
                            ID = 7,
                            Age = (short)25,
                            Email = "cemparlar@gmail.com",
                            IdentityNo = "12345678947",
                            LastName = "Parlar",
                            Name = "Cem",
                            Password = "123456782",
                            Sex = "m"
                        },
                        new
                        {
                            ID = 8,
                            Age = (short)27,
                            Email = "yagmurunal@gmail.com",
                            IdentityNo = "12345678948",
                            LastName = "Unal",
                            Name = "Yagmur",
                            Password = "123456783",
                            Sex = "f"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
